#ifndef __DEF__
#define __DEF__

enum LVM_CMD{
    LVM_CMD_CREATLVM = 100,
    LVM_CMD_SETTIMER = 110, 
    LVM_CMD_ONTIMER = 111,
    LVM_CMD_KILLTIMER = 112,
    LVM_CMD_HTTP_REQ = 120,
    LVM_CMD_HTTP_RESP = 121,
    LVM_CMD_CLIENT_MSG = 130,
    LVM_CMD_CLIENT_MSG_BACK = 131,
    LVM_CMD_CLIENT_CONN = 140,
    LVM_CMD_CLIENT_DISCONN = 141       
};

#endif