

local M = {
    LVM_CMD_CREATLVM = 100,
    LVM_CMD_DELLVM = 101,
    LVM_CMD_SEND_LVMMSG = 103,
    LVM_CMD_RET_LVMMSG = 104,
    LVM_CMD_SETTIMER = 110,     
    LVM_CMD_ONTIMER = 111,
    LVM_CMD_KILLTIMER = 112,
    LVM_CMD_HTTP_REQ = 120,
    LVM_CMD_HTTP_RESP = 121,
    LVM_CMD_CLIENT_MSG = 130,
    LVM_CMD_CLIENT_MSG_BACK = 131,
    LVM_CMD_CLIENT_CONN = 140,
    LVM_CMD_CLIENT_DISCONN = 141,
    LVM_CMD_CLIENT_CLOSE = 142,
}


return M